-- Active: 1738011862925@@127.0.0.1@3306@test
CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE post (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user INT REFERENCES user(id),
  title VARCHAR(50) NOT NULL,
  description TEXT NOT NULL
);

